### PR TITLE
migrate del_load_balancer method

### PR DESCRIPTION
**Pull request by sam-falvo**

### CODE REVIEW

**Comment by glyph** [comment]
Since tests are still failing I'm going to tag this as WIP.

**Comment by sam-falvo** [comment]
My tests pass.

On Fri, May 8, 2015 at 2:37 PM, Glyph <notifications@github.com> wrote:

> Since tests are still failing I'm going to tag this as WIP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackerlabs/mimic/pull/253#issuecomment-100375098>.
>



-- 
Samuel A. Falvo II

**Comment by glyph** [comment]
Sorry, by "tests" I mean "statuses" - specifically the coveralls coverage dropping.  Looks like travis will actually pass.

**Comment by glyph** [comment]
The issue is that `_verify_and_update_lb_state` was copied, but not fully moved, so some of the tests are hitting the new one and some are hitting the old one.  For now, probably best to just import it, since a bunch of existing methods in the `canned_responses` module are still using the old version.

**Comment by sam-falvo** [comment]
Ahh, you had me scared there.  I don't know how to fix coverall's problem except to migrate more and more methods to exercise various conditions in _verify_lb_...() function, since that's what it's complaining about.

**Comment by glyph** [comment]
In support of #244.

**Comment by sam-falvo** [comment]
Duplicates work performed by @kivattik

**Pull request closed without merging**
