### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by glyph**

### CODE REVIEW

**Comment by cyli** [comment]
YAY!  Can we merge this?

**Comment by glyph** [comment]
I'm somewhat surprised to see all the tests passing, given that this now updates testtools and pbr!

**Comment by cyli** [comment]
@glyph `tox.ini` does not install the things listed in `requirements.txt`, and certainly not from `dev-requirements.txt` - hence #199

**Comment by glyph** [comment]
https://requires.io/github/rackerlabs/mimic/requirements/?branch=master says:

> Requires.io looks for the following requirements files in the project:

> - `setup.py`,

but I don't see an update to `setup.py` here; maybe it can't parse it with all our wacky procedural mac app stuff in the way?

**Comment by glyph** [comment]
This is hopelessly out of date; hopefully requires.io will reopen against master.

**Pull request closed without merging**
