### PR TITLE
Remove dev-requirements

### PR DESCRIPTION
**Pull request by cyli**
Since it wasn't really being maintained, and the testing requirements were installed in `setup.py` anyway.

And just copied all the requirements from `setup.py` to `requirements.txt`.

Question: should we just get rid of `requirements.txt` and everyone can just `pip install -e .`?

### CODE REVIEW

**Comment by glyph** [comment]
I will put comments on #199 since I think that's what this is a part of :)

**Comment by glyph** [comment]
Or rather, I'll put comments relevant to the general design there.

**Comment by glyph** [comment]
Can you revert out the parts of this which change `requirements.txt`?  The reason that `requirements.txt` is different from `setup.py` is that `requirements.txt` should always be pinned and `setup.py` should never be unless we know something is broken.  See [the canonical holy text](https://caremad.io/2013/07/setup-vs-requirement/) on this subject.

**Comment by cyli** [comment]
@glyph Ah ok, sure.  This change also adds testtools to `requirements.txt` - should I pin that version?  Or should I leave it out of `requirements.txt` entirely?

**Comment by glyph** [comment]
Pinning that version would be good.

**Comment by glyph** [comment]
It looks like `getting-started.rst` still has a couple of references to `dev-requirements.txt`; those need to be updated to do something else.  And this is why `dev-requirements.txt` still exists, I think - there isn't really a good way to do what those instructions propose if we *don't* ship a `dev-requirements.txt`.  So I think this is going to need to be more holistic in how it addresses things, and actually move the requirements out of the travis config and into a `requirements/` directory as independent `.txt` files.

**Comment by cyli** [comment]
Closing this in favor of a better solution.

**Pull request closed without merging**
