### PR TITLE
Adding py3 support

### PR DESCRIPTION
**Pull request by lekhajee**
- adds py34 to tox
- allows the py34 build to fail without failing travis
- updates requirements to install twisted 15.4 
- removes references to old logging in twisted
- makes `random_hex_generator` py3 compatible
- Changes urllib to six.moves.urllib.parse to support both py27 and py34

### CODE REVIEW

**Comment by glyph** [comment]
@lekhajee - Would you mind updating this so that it's an allow-fail build, so we can put this on trunk and at least be aware if other changes make it worse while we're working on it?

**Comment by glyph** [comment]
This needs a `setup.py` version bump as well.

**Comment by glyph** [comment]
For Twisted, I mean; right now it still says `>=14.0.2` but we are dropping those versions from our test matrix.

**Comment by glyph** [comment]
I think we should land this before making too many other py3 changes and making it too hard to review - so please just adjust distutils metadata and land :)

**Comment by ksheedlo** [comment]
Where does this change leave py26 support? #318

**Comment by glyph** [comment]
@ksheedlo - we haven't killed it yet… ;). (Nor should *this* change kill it.  This should be just to get the tests bootstrapped.  We may well want to kill it in a subsequent PR before we get to move `py34` out of `allow_failures` though)

**Comment by ksheedlo** [comment]
Sounds good to me.

**Pull request merged**
