### PR TITLE
Fix reqs so Cloud Monitoring can run against Mimic

### LINKED ISSUE #502: Pip install -r requirements/development.txt fails
This happens due to wheels being defined in both lint and documentation which are invoked from development.
```
Double requirement given: wheel==0.24.0 (from -r requirements/lint.txt (line 6)) (already in wheel==0.24.0 (from -r requirements/documentation.txt (line 17)), name='wheel')
Storing debug log for failure in /var/folders/vh/2my6rmp55lx41gsg_m425dcw0000gn/T/tmpKsdTyw
```

### PR DESCRIPTION
**Pull request by kaustavha**
This PR does 3 minor things.
- `pip install development.txt` would fail with a python pip error citing duplicate requirements. There is a related pr in pip as well https://github.com/pypa/pip/pull/3372 but I think it makes sense to fix this on mimic for other people using it with older versions of pip; although I understand and sympathize with the idea of a more modular requirements txt. 
- Running `python setup.py install` after `pip install development.txt` would fail citing a missing pyasn1. This fixes that. 
- linecache2 does not seem to be used anywhere and when attempting to install mimic in ele the following error plagues my console:

 ```
==> default:   File "build/bdist.linux-x86_64/egg/linecache2/tests/inspect_fodder2.py", line 102
==> default:     def keyworded(*arg1, arg2=1):
==> default:                             ^
==> default: SyntaxError: invalid syntax
==> default:
==> default:   File "/data/mimic-env/lib/python2.7/site-packages/linecache2-1.0.0-py2.7.egg/linecache2/tests/inspect_fodder2.py", line 102
==> default:     def keyworded(*arg1, arg2=1):
==> default:                             ^
==> default: SyntaxError: invalid syntax
```

This closes #502

### CODE REVIEW

**Comment by glyph** [comment]
We definitely need `linecache2` in there. That output looks like it's coming from a Chef recipe or something, not anything within pip or mimic.  What command provokes it?

You can tell `linecache2` is necessary by installing mimic and then watching what `pip` does:

```console
$ mktmpenv ; cd - 
New python executable in tmp-2fc42912d4d1b327/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
/Users/glyph/Projects/Mimic
(tmp-2fc42912d4d1b327)$ pip install -e .
Obtaining file:///Users/glyph/Projects/Mimic
Collecting characteristic>=14.2.0 (from mimic==2.0.0)
  Using cached characteristic-14.3.0-py2.py3-none-any.whl
Collecting klein>=15.3.1 (from mimic==2.0.0)
  Using cached klein-15.3.1-py2.py3-none-any.whl
Collecting twisted>=15.5.0 (from mimic==2.0.0)
Collecting jsonschema>=2.0 (from mimic==2.0.0)
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting treq>=15.1.0 (from mimic==2.0.0)
  Using cached treq-15.1.0-py2.py3-none-any.whl
Collecting six>=1.6.0 (from mimic==2.0.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting xmltodict>=0.9.1 (from mimic==2.0.0)
Collecting attrs>=15.1.0 (from mimic==2.0.0)
  Using cached attrs-15.2.0-py2.py3-none-any.whl
Collecting testtools<1.8.0,>=1.7.1 (from mimic==2.0.0)
  Using cached testtools-1.7.1-py2.py3-none-any.whl
Collecting iso8601>=0.1.10 (from mimic==2.0.0)
  Using cached iso8601-0.1.11-py2.py3-none-any.whl
Collecting toolz>=0.7.4 (from mimic==2.0.0)
Collecting werkzeug (from klein>=15.3.1->mimic==2.0.0)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting zope.interface>=3.6.0 (from twisted>=15.5.0->mimic==2.0.0)
Collecting functools32 (from jsonschema>=2.0->mimic==2.0.0)
Collecting service-identity>=14.0.0 (from treq>=15.1.0->mimic==2.0.0)
  Using cached service_identity-14.0.0-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.13 (from treq>=15.1.0->mimic==2.0.0)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting requests>=2.1.0 (from treq>=15.1.0->mimic==2.0.0)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting traceback2 (from testtools<1.8.0,>=1.7.1->mimic==2.0.0)
  Using cached traceback2-1.4.0-py2.py3-none-any.whl
Collecting extras (from testtools<1.8.0,>=1.7.1->mimic==2.0.0)
Collecting unittest2>=1.0.0 (from testtools<1.8.0,>=1.7.1->mimic==2.0.0)
  Using cached unittest2-1.1.0-py2.py3-none-any.whl
Collecting python-mimeparse (from testtools<1.8.0,>=1.7.1->mimic==2.0.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/glyph/.virtualenvs/tmp-2fc42912d4d1b327/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted>=15.5.0->mimic==2.0.0)
Collecting pyasn1-modules (from service-identity>=14.0.0->treq>=15.1.0->mimic==2.0.0)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity>=14.0.0->treq>=15.1.0->mimic==2.0.0)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
  Using cached cryptography-1.2.1-cp27-none-macosx_10_6_intel.whl
Collecting linecache2 (from traceback2->testtools<1.8.0,>=1.7.1->mimic==2.0.0)
  Using cached linecache2-1.0.0-py2.py3-none-any.whl
Collecting argparse (from unittest2>=1.0.0->testtools<1.8.0,>=1.7.1->mimic==2.0.0)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=0.7->pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
Collecting ipaddress (from cryptography>=0.7->pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=0.7->pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
  Downloading cffi-1.5.0-cp27-none-macosx_10_6_intel.whl (215kB)
    100% |████████████████████████████████| 217kB 2.2MB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->pyOpenSSL>=0.13->treq>=15.1.0->mimic==2.0.0)
Installing collected packages: characteristic, werkzeug, zope.interface, twisted, klein, functools32, jsonschema, six, enum34, ipaddress, pyasn1, idna, pycparser, cffi, cryptography, pyOpenSSL, pyasn1-modules, service-identity, requests, treq, xmltodict, attrs, linecache2, traceback2, extras, argparse, unittest2, python-mimeparse, testtools, iso8601, toolz, mimic
  Running setup.py develop for mimic
Successfully installed argparse-1.4.0 attrs-15.2.0 cffi-1.5.0 characteristic-14.3.0 cryptography-1.2.1 enum34-1.1.2 extras-0.0.3 functools32-3.2.3.post2 idna-2.0 ipaddress-1.0.16 iso8601-0.1.11 jsonschema-2.5.1 klein-15.3.1 linecache2-1.0.0 mimic-2.0.0 pyOpenSSL-0.15.1 pyasn1-0.1.9 pyasn1-modules-0.0.8 pycparser-2.14 python-mimeparse-0.1.4 requests-2.9.1 service-identity-14.0.0 six-1.10.0 testtools-1.7.1 toolz-0.7.4 traceback2-1.4.0 treq-15.1.0 twisted-15.5.0 unittest2-1.1.0 werkzeug-0.11.3 xmltodict-0.9.2 zope.interface-4.1.3
(tmp-2fc42912d4d1b327)$ pip freeze | grep linecache2
linecache2==1.0.0
(tmp-2fc42912d4d1b327)$ 
```

**Comment by glyph** [comment]
This does highlight a known problem with our CI: we don't have anything currently that validates that the various requirements files completely satisfy their transitive dependency graph.

**Comment by kaustavha** [comment]
@glyph I have reverted the removal of linecache2.

**Comment by glyph** [comment]
> pip install development.txt would fail with a python pip error citing duplicate requirements. There is a related pr in pip as well pypa/pip#3372 but I think it makes sense to fix this on mimic for other people using it with older versions of pip; although I understand and sympathize with the idea of a more modular requirements txt.

This PR duplicates a bunch of additional dependencies, which creates yet more duplicate data to manage.  The whole point of organizing the requirements under `requirements/*.txt` was to remove the duplication we had previously.

Could you instead maybe make a `common.txt` (maybe containing only the `wheel` requirement?) and then have `documentation-only.txt` and `lint-only.txt` files without the common requirements?  Then `development.txt` could be `-r common.txt`, `-r documentation-only.txt` `-r lint-only.txt`; `documentation.txt` could be just `-r common.txt`, `-r documentation-only.txt`.  This retains the "public interface" of this directory (i.e., no changes to `tox.ini`) and creates no duplication.

> Running python setup.py install after pip install development.txt would fail citing a missing pyasn1. This fixes that.

`development.txt` is a listing of the *development tools* that we use to work on Mimic.  It is not supposed to satisfy all the dependencies of mimic itself.  That is what `production.txt` is for.  It sounds like maybe you should not be attempting to install `development.txt` at all in this environment?

**Comment by kaustavha** [comment]
@glyph made suggested changes

**Comment by glyph** [comment]
@kaustavha - looks like the build is failing because `lint.txt` still includes `wheel`. Can you update that?

**Comment by kaustavha** [comment]
@glyph ah whoops, my bad. Fixed

**Comment by glyph** [comment]
Thanks for sorting this out @kaustavha .  :shipit:

**Pull request merged**
