### PR TITLE
refactor(maas_api): cleanup suggestions from #79

### PR DESCRIPTION
**Pull request by ksheedlo**

### CODE REVIEW

**Comment by ksheedlo** [comment]
https://github.com/rackerlabs/mimic/pull/79#discussion_r22687905, https://github.com/rackerlabs/mimic/pull/79#discussion_r22688542

**Comment by ksheedlo** [comment]
https://github.com/rackerlabs/mimic/pull/79#discussion_r22687605

**Comment by lekhajee** [comment]
@ksheedlo : please fix conflicts

**Comment by ksheedlo** [comment]
@lekhajee: Updated.

**Comment by lekhajee** [comment]
+1

**Pull request merged**
