### PR TITLE
Debugging coverage

### PR DESCRIPTION
**Pull request by stevepeak**
Debugging coverage, please do not merge. Thanks!

### CODE REVIEW

**Comment by stevepeak** [comment]
I'm not sure whats going on here. It appears to be an issue with coverage.py as seen here:

- [Line 1285][1] shows the pickled coverage data looks accurate.
- [Line 1295][2] shows coveragepy failing.

Seem to be an issue with coveragepy-v4.0. https://travis-ci.org/rackerlabs/mimic/jobs/81638534#L887

[1]: https://travis-ci.org/rackerlabs/mimic/jobs/81637380#L1285
[2]: https://travis-ci.org/rackerlabs/mimic/jobs/81637380#L1295

**Comment by tawalton** [comment]
@stevepeak +1 to creating an issu on ned/coveragepy

**Comment by stevepeak** [comment]
https://bitbucket.org/ned/coveragepy/issues/408/coverageexception-doesnt-seem-to-be-a

**Comment by stevepeak** [comment]
The commits above are attempting to create the `coverage.xml` during the `tox` process to ensure the correct version of coveragepy is used when generating the report.

**Comment by stevepeak** [comment]
Bingo!

**Comment by tawalton** [comment]
@stevepeak Thanks for debugging and fixing this

**Comment by stevepeak** [comment]
@tawalton my pleasure! I wish I had a better fix, but not sure that is possible when installing codecov via pip.

**Comment by ksheedlo** [comment]
my-brain-is-full-of-fuck

**Comment by ksheedlo** [comment]
@stevepeak I'm lost. Can you explain how this fix actually works?

**Comment by stevepeak** [comment]
@ksheedlo the issue is `pip install codecov` is installed outside the tox env (from what I saw). Then coveragepy 3.7.1 was installed inside the tox env which created the discrepancy. Here is an illustration:

```
   +----Travis Python Env--------------+        
   |  pip install codecov              |        
   |        -> coverage v4.0           |        
   |     +------Tox Env----------+     |        
   |     |  covarege 3.7.1       |     |        
   |     |  tests run            |     |        
   |     |  .coverage file       |     |        
   |     |                       |     |        
   |     +-----------------------+     |        
   |   $ codecov                       |        
   |     Cals `coverage xml`           |
   |     Fails bc 4.0 vs 3.7.1 data    |        
   |                                   |        
   +-----------------------------------+        
```
> `codecov` detects no reports but finds the `.coverage` data file (v3.7.1). `codecov` will then call `coverage xml -i` (which is v4.0) => fails because of conflicting `.coverage` versions.

-----

```
   +----Travis Python Env--------------+        
   |  pip install codecov              |        
   |        -> coverage v4.0           |        
   |     +------Tox Env----------+     |        
   |     |  covarege 3.7.1       |     |        
   |     |  tests run            |     |        
   |     |  .coverage file       |     |        
   |     |  $ coverage xml       |     |        
   |     +-----------------------+     |        
   |   $ codecov                       |        
   |      works bc xml exists already  |        
   |                                   |        
   +-----------------------------------+        
```
> Calling `coverage xml` within the toxenv will produce the `coverage.xml` report. When `codecov` is called it will find the coverage report and **not** call `coverage xml -i`.

------

I wish I could just send the `.coverage` data to Codecov, but the data is not mapped out with the source yet. So at this point I am required to call `coverage xml` to create a report that has enough data for Codecov to work with. In the future I would like to create our own plugin to parse the pickled data.

**Comment by ksheedlo** [comment]
@stevepeak Thanks for the write-up! LGTM

**Pull request merged**
