### PR TITLE
refactor(MaasApi): clean and beautify code

### PR DESCRIPTION
**Pull request by ksheedlo**

### CODE REVIEW

**Comment by ksheedlo** [comment]
Let's hold this for a bit. I have a more interesting MaaS refactor coming.

**Comment by ksheedlo** [comment]
I do want to have some version of this change make it in, but please give priority to #418 in reviewing. I'd rather land that one first.

**Comment by ksheedlo** [comment]
Ready for review.

**Comment by glyph** [comment]
I definitely prefer the more functional style of value construction here, and it sets a better example for future code.  Thanks for taking the time to do this.

**Pull request merged**
