### PR TITLE
Try avoiding 'push' builds on non-master branches.

### PR DESCRIPTION
**Pull request by glyph**
We'll typically have PRs for these.

### CODE REVIEW

**Comment by glyph** [comment]
Documentation reference: http://docs.travis-ci.com/user/build-configuration/

**Comment by glyph** [comment]
Looks like it had the desired effect, and travis is only building the "pr" builder.

**Comment by lekhajee** [comment]
could we also include the `gh-pages` branch.

**Comment by lekhajee** [comment]
+1 modulo the comment

**Comment by glyph** [comment]
I added the label https://github.com/rackerlabs/mimic/labels/good%20to%20land%20%28with%20minor%20changes%29 to indicate an approved-but-pending-changes-that-don't-need-to-be-reviewed; would that be appropriate here?

**Comment by lekhajee** [comment]
> I added the label https://github.com/rackerlabs/mimic/labels/good%20to%20land%20%28with%20minor%20changes%29 to indicate an approved-but-pending-changes-that-don't-need-to-be-reviewed; would that be appropriate here?

+1, updated the label. Thanks :)

**Comment by glyph** [comment]
Sigh. Re-poking Travis.

**Comment by glyph** [comment]
Thanks for noticing the `gh-pages` thing, by the way. That was a very good catch.

**Comment by lekhajee** [comment]
@glyph: welcome! Trained by you :)

**Pull request merged**
