### PR TITLE
Fix for new setuptools

### PR DESCRIPTION
**Pull request by glyph**
Looks like `pkg_resources` picked up a new dynamic import.

### CODE REVIEW

**Comment by glyph** [comment]
I think that we might want to land this even though `setuptools` has un-released 20.2.1 just as it un-released 20.2.0; it seems clear that a new release of setuptools is going to start depending on new packages from `pkg_resources._vendor` whenever a non-buggy version of 20.2.x comes out.

**Comment by glyph** [comment]
I've merged master to trigger a new build, to ensure that this works on "old" setuptools as well.

**Comment by glyph** [comment]
@manishtomar - if you could do a quick review once the tests have passed, that would be great

**Comment by manishtomar** [comment]
:+1:

**Pull request merged**
