### PR TITLE
Initial take on JSON read decorator

### PR DESCRIPTION
**Pull request by kivattik**
Addresses #226

### CODE REVIEW

**Comment by glyph** [comment]
Just a lint failure… https://travis-ci.org/rackerlabs/mimic/jobs/61926626

**Comment by glyph** [comment]
Just to be clear, my previous comment was just a poke to remind you to look at the build failure, not a review :).  Is this RFR?  Should I review it?

**Comment by lekhajee** [comment]
@kivattik : bump.

**Comment by lekhajee** [comment]
@kivattik : bump

**Comment by glyph** [comment]
This has been idle for a while, and this work should probably take place in https://github.com/twisted/klein anyway - let's resume it there.

**Pull request closed without merging**
