### PR TITLE
RFR: test(auth): multiple tokens per session

### PR DESCRIPTION
**Pull request by ksheedlo**
This change is a follow up to #209. It adds an integration test that was
requested in code review.

### CODE REVIEW

**Comment by ksheedlo** [comment]
I don't know if I can verify that both tokens are accessing the same session given the current dummy `ExampleAPI`. See the comment included in the diff.

@lekhajee do you have any ideas on what we should do here?

**Comment by lekhajee** [comment]
@ksheedlo : We can verify that the `username` in the service catalog match.

**Comment by lekhajee** [comment]
+1, good to merge once the build on travis is successful :)

**Comment by ksheedlo** [comment]
cool, thanks!

**Pull request merged**
