### PR TITLE
upgrade code quality tools

### PR DESCRIPTION
**Pull request by glyph**
linter, documentation, etc.

this depends on #497 and is an example of how upgrading dependencies will be more straightforward once that lands.

### CODE REVIEW

**Comment by glyph** [comment]
a more useful diff to look at, in the meanwhile: https://github.com/glyph/mimic/compare/requirements-sanity...glyph:better-linter

**Comment by glyph** [comment]
The correct diff is https://github.com/rackerlabs/mimic/compare/master...glyph:better-linter

**Comment by tawalton** [comment]
just looking at the the link provided above -- LGTM

**Comment by glyph** [comment]
thanks @tawalton !

**Pull request merged**
