### PR TITLE
fix(maas_api): correctly determine hostname

### LINKED ISSUE #396: Hard coded port in maas_api
https://github.com/rackerlabs/mimic/blob/9a9ea300fc7b934ad8494fcabe22daeb0f044056/mimic/rest/maas_api.py#L362

Has the port number hard coded to 8900.

We recently started running mimic in a container on our build slaves. It is possible to force it to bind to local port 8900 and make this work. But ideally we would want Jenkins to manage the ports.

### PR DESCRIPTION
**Pull request by ksheedlo**
Fixes #396.

### CODE REVIEW

**Comment by ksheedlo** [comment]
Needs tests.

**Comment by ksheedlo** [comment]
Update: added tests.

**Comment by ksheedlo** [comment]
Update: added moar tests.

**Comment by glyph** [comment]
LGTM; pretty straightforward, thanks for the softball :).

**Pull request merged**
