### PR TITLE
fix(maas): always encode text utf-8

### LINKED ISSUE #312: MAAS API should support Unicode
I tried to make a MAAS entity called "🐴entity" and Mimic failed. It looks like it only supports ASCII. I want to test out Unicode support in Intelligence but this isn't good for working with Mimic.

Here are the stack trace and log statement.

```
2015-06-11 22:38:34-0700 [HTTPChannel,97,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
	    body = resrc.render(self)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/klein/resource.py", line 195, in render
	    d = defer.maybeDeferred(_execute)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/klein/resource.py", line 189, in _execute
	    **kwargs)
	--- <exception caught here> ---
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/klein/app.py", line 100, in execute_endpoint
	    return endpoint_f(self._instance, *args, **kwargs)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/klein/app.py", line 185, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "/Users/ken/rackerlabs/mimic/python_env/lib/python2.7/site-packages/klein/app.py", line 29, in _call
	    return f(instance, *args, **kwargs)
	  File "/Users/ken/rackerlabs/mimic/mimic/rest/maas_api.py", line 357, in create_entity
	    newentity = create_entity(postdata)
	  File "/Users/ken/rackerlabs/mimic/mimic/rest/maas_api.py", line 121, in create_entity
	    newentity['label'] = params[u'label'].encode("ascii")
	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

2015-06-11 22:38:34-0700 [HTTPChannel,97,127.0.0.1] "127.0.0.1" - - [12/Jun/2015:05:38:33 +0000] "POST /mimicking/MaasApi-38bc5d/ORD/v1.0/921648/entities HTTP/1.1" 500 95 "http://localhost:3000/cloud/entities" "Rackspace Intelligence; username_bb4dc1b8-3c02-4721-94ea-3116346b564d; 921648"
```

### PR DESCRIPTION
**Pull request by ksheedlo**
Turns out we can have nice things, if we try.

Fixes #312.

### CODE REVIEW

**Comment by lekhajee** [comment]
@ksheedlo : could you add a test to try and create the entity "🐴entity" or such :)

**Comment by ksheedlo** [comment]
sure!

**Comment by ksheedlo** [comment]
I'm having opsy issues with Python on my Mac again. Bear with me, I'll get the test case in when I can fix them.

**Comment by ksheedlo** [comment]
I missed one from the other PR. Stand by for another update.

**Comment by ksheedlo** [comment]
Update: Fixed. Strings in the MAAS API are converted to UTF-8.

**Comment by lekhajee** [comment]
+1. Good to merge when the tests pass on travis

**Pull request merged**
