### PR TITLE
Enhancement: missing identity token generation test

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
- seems there is a branch that was not being tested or covered;
  this adds a specific test for the branching mechanism to cover
  both branch possibilities.

### CODE REVIEW

**Comment by glyph** [comment]
This looks great. But unfortunately I merged something else first, so I can't land this.  I'm starting to wonder if we should switch to a branching, rather than forking model, so that reviewers can hit the "update branch" button :-\

**Comment by glyph** [comment]
Can you merge trunk and then land?

**Comment by BenjamenMeyer** [comment]
@glyph probably a mix...things like my External API stuff probably would be good (better?) on a branch; but little stuff like this is fine in a fork.

**Comment by BenjamenMeyer** [comment]
tests passed merged as requested

**Pull request merged**
