### PR TITLE
replace nth_endpoint_public in test_same_tenant_different_regions

### PR DESCRIPTION
**Pull request by glyph**

### CODE REVIEW

**Comment by cyli** [comment]
It looks like `test_different_tenants_same_region_different_lbs` also uses `nth_endpoint_public`.

**Comment by glyph** [comment]
That is handled by #279. Small PRs! :)

**Comment by glyph** [comment]
Still looks good to you?

**Comment by cyli** [comment]
Yes.

**Comment by glyph** [comment]
Thanks for the review!

**Pull request merged**
