### PR TITLE
don't depend on implicit behavior, removed in recent twisted

### PR DESCRIPTION
**Pull request by glyph**
Fix the Dockerfile to actually *install* the software.

### CODE REVIEW

**Comment by Kuwagata** [comment]
👍  Confirmed that the container starts up successfully.

**Comment by glyph** [comment]
Thanks for reporting and testing @Kuwagata !  I'll hit the green button as soon as Travis is done.

**Comment by everett-toews** [comment]
👍

**Comment by glyph** [comment]
Thanks for the second look @everett-toews !  I was just waiting for CI to pass (Travis has been having a hard week) but it's always nice to get more reviewers :).

**Pull request merged**
