### PR TITLE
RFR: feat(maas): add /alarm_examples endpoint

### PR DESCRIPTION
**Pull request by ksheedlo**
Resubmitting per @glyph's request on #139.

### CODE REVIEW

**Comment by glyph** [comment]
Thanks!

**Comment by ksheedlo** [comment]
@glyph is that a +1? You know I don't have push access to this repo.

@lekhajee +1'd the earlier PR and this one is really just a cherry-pick, in case that changes anything.

**Comment by glyph** [comment]
@ksheedlo I was just saying "thanks" for doing the resubmission. I haven't had time to review yet - and I think that @tokunbo should have a look before landing since he knows more about the monitoring stuff anyway.  On this repo we have generally been doing reviewer-merges, so a +1 (or would it be a +2?  a merge approval, anyway) will result in it landing on master :).

**Comment by ksheedlo** [comment]
@glyph Sounds good!

**Comment by lekhajee** [comment]
+1. Will wait for @tokunbo to look at it tomorrow and will merge it.

**Comment by lekhajee** [comment]
@ksheedlo : also, gave you access to merge PRs.

**Comment by tokunbo** [comment]
+1 .....do the dew!

**Pull request merged**
