### PR TITLE
Implement keystone get_version

### PR DESCRIPTION
**Pull request by Benjamin91300**
Recent novaclient versions and openstackclient require keystone
resource /identity/v2.0. This commit provides it.

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
I believe this should resolve part of #511

**Comment by BenjamenMeyer** [comment]
Rekicking the Travis build. The Pypy build failed for some odd reason not related to this PR.

**Comment by Benjamin91300** [comment]
Thanks Benjamin !

**Comment by BenjamenMeyer** [comment]
LGTM (:+1:)

@Benjamin91300 you need to merge master; after that and tests pass, then it should be pretty straight forward to a merge once one of the cores can review; I think they're all at/prepping for PyCon right now.

**Comment by Benjamin91300** [comment]
Hi Benjamen,

I have update the branch using automatic fonction "update branch".
I hope it's enough, otherwise I will make a manual rebase from my local repo.

Regards.

**Comment by BenjamenMeyer** [comment]
@Benjamin91300 that should be good enough unless there are conflicts from the merge, which I believe if that's the case it won't let you do the update that way.

**Comment by BenjamenMeyer** [comment]
Just to note: even adding the parameter to the `openstack` command provided by `python-openstackclient` to set the Identity version does not make it work without being able to list the version. :person_frowning: and `python-keystoneclient` no longer installs a command-line interface.

@Benjamin91300 could you also modify the primary README file to update information related to the querying for the service catalog via the `openstack` command, example: `openstack --os-project-name mimic --os-username mimic --os-password 1235 --os-auth-url http://localhost:8900/identity/v2.0/ --os-identity-api-version 2 --insecure catalog show` (I haven't gotten that to work on mine yet, so try it out first.). This way people can just copy/paste the against to validate it. Presently only the `curl` command works. Thanks!

**Comment by glyph** [comment]
@Benjamin91300 - sadly this needs another update due to other changes in the meanwhile.  Could you update the branch?  Thanks!

**Comment by Benjamin91300** [comment]
New version after a rebase...

**Comment by glyph** [comment]
@Benjamin91300 - I was going to hit the merge button but reviewing another PR first put this one out of date again :)  Sorry!  Github doesn't give me access to update your branches automatically...

**Comment by Benjamin91300** [comment]
Another rebase then ;-)

**Comment by glyph** [comment]
Quick, before anyone else merges anything ;-)

**Pull request merged**
