### PR TITLE
move CLB add_node to the clb object

### PR DESCRIPTION
**Pull request by kivattik**

### CODE REVIEW

**Comment by glyph** [comment]
The ☂ label is intended to be only for the top-level thing, not for everything that falls under one of those things :).

**Comment by glyph** [comment]
I think what you meant by attaching ☂ was "in support of #244?

**Comment by kivattik** [comment]
Yep, that is what I meant.

**Comment by glyph** [comment]
Also looks pretty straightforward, address merge conflicts and land when ready.

**Pull request merged**
