### PR TITLE
WIP - Add Support to mimic CDN providers

### PR DESCRIPTION
**Pull request by malini-kamalambal**
This PR adds support to mimic CDN provider API calls. While this might not fit in the scope of Mimic (since this does not mock Openstack endpoints, but is aimed at mocking Fastly API calls), the intent of this PR is to get feedback on if this is the right approach. If this turns out to fit into the Mimic context & can be merged, I can clean up this PR & add tests.

### CODE REVIEW

**Comment by glyph** [comment]
@malini-kamalambal I feel compelled to point out that it is in fact early next year :smile:

**Comment by wbrothers** [comment]
I am working on a this code and getting prepared for a pull request.

I have been working on the code for the tests for this new functionality.

I will have a PR for Akamai either this week or next.

Feel free to reach out to me if you have any questions.

Thanks,
Bill


William Brothers

Software Developer Test III

Rackspace Hosting 3080 Premiere Pkwy Suite 115 Duluth, GA 30097

william.brothers@rackspace.com<mailto:william.brothers@rackspace.com>

770-813-1622

Adaptability * Context * Includer * Empathy * Achiever

________________________________

**Comment by glyph** [comment]
Trying to update some metadata to reflect the current state of the comments - @wbrothers, you are working on this, and it's not ready for a review / merge yet?

**Comment by wbrothers** [comment]
I am going to close this pr. PR #142 replaces this one.

**Comment by glyph** [comment]
Thanks!

**Pull request closed without merging**
